id: ADF9B94C1
base_file: fFD5A.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:06:40.163430
  last_modified_at: 2022-05-31 05:06:40.163435
