id: ADF9B94C1
base_file: f40E9.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:06:40.160135
  last_modified_at: 2022-05-31 05:06:40.160140
