id: ADF9B94C1
base_file: f4F8C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:06:40.161732
  last_modified_at: 2022-05-31 05:06:40.161735
